TARGET  := ftpd

CFILES  := $(wildcard source/*.c)
OFILES  := $(patsubst source/%,build.linux/%,$(CFILES:.c=.o))

CFLAGS  := -g -Wall -Iinclude -DSTATUS_STRING="\"ftpd v$(VERSION)\""
LDFLAGS :=

.PHONY: all clean

all: build.linux $(TARGET)

build.linux:
	@mkdir build.linux/

$(TARGET): $(OFILES)
	@$(CC) -o $@ $^ $(LDFLAGS)

$(OFILES): build.linux/%.o : source/%.c
	@$(CC) -o $@ -c $< $(CFLAGS)

clean:
	@$(RM) -r build.linux/ $(TARGET)
